name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies for frontend
      working-directory: ./frontend
      run: |
        npm install --legacy-peer-deps
        npm audit fix

    - name: Install dependencies for backend
      working-directory: ./backend
      run: |
        npm install --legacy-peer-deps
        npm audit fix

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

    - name: Build backend
      working-directory: ./backend
      run: npm run build

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend Docker image
      run: |
        docker build -t ${DOCKER_USERNAME}/frontend:latest -f ./frontend/Dockerfile ./frontend
        docker push ${DOCKER_USERNAME}/frontend:latest

    - name: Build and push backend Docker image
      run: |
        docker build -t ${DOCKER_USERNAME}/backend:latest -f ./backend/Dockerfile ./backend
        docker push ${DOCKER_USERNAME}/backend:latest

    - name: Deploy containers
      run: |
        docker-compose down
        docker-compose up -d
